language: python

python:
    - "2.6"
    - "2.7"

before_install:
    - deactivate
    - if test $(python --version 2>&1 | cut -d '.' -f 2) -eq 6; then wget -O- http://neuro.debian.net/lists/precise.us-nh.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list; fi
    - sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
    - sudo apt-get update -qq
    - sudo apt-get install -qq python-scipy python-nose python-nibabel python-sklearn ; fi
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate

install:
    - python setup.py install

script:
    - make clean
    - make test-code
