language: python

virtualenv:
  system_site_packages: true

env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="2.7"
    - DISTRIB="ubuntu-no-matplotlib" PYTHON_VERSION="2.7"
    - DISTRIB="neurodebian" PYTHON_VERSION="2.7" COVERAGE="true"
    - DISTRIB="conda" PYTHON_VERSION="2.6"
      NUMPY_VERSION="1.9.1" SCIPY_VERSION="0.15.1"
      MATPLOTLIB_VERSION="1.4.2" SKLEARN_VERSION="0.15.2"

install: 
    - source continuous_integration/install.sh

before_script:
    - make clean

script:
    - python continuous_integration/show-python-packages-versions.py
    # Copy setup.cfg to /tmp where we are going to run the tests from
    # Mainly for nose config settings
    - cp setup.cfg /tmp
    # We want to back out of the current working directory to make
    # sure we are using nilearn installed in site-packages rather
    # than the one from the current working directory
    # Parentheses (run in a subshell) are used to leave
    # the current directory unchanged
    - (cd /tmp && make -f $OLDPWD/Makefile test-code)

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
